- hosts: all
  tasks: 
    - name: install packages
      dnf:
        name: "{{ item }}"
        state: latest
      with_items:
      - sudo
      - vim
      - htop
      - iotop
      - wget
      - tar
      - libselinux-python
      - python-urlgrabber
      - python2-pycurl
      - python2-pygpgme
      - pyxattr
      - yum-metadata-parser
      - yum 
      - screen
      - gtk3
      - Xorg
      - libXv
      - twm
      - libXNVCtrl
      - xdm
      - xhost
    - name: reboot on panic
      sysctl:
        name: kernel.panic
        value: 10
        state: present
  tags: packages
  become: yes

- hosts: all
  roles:
     - singleplatform-eng.users
  tags: users
  become: yes

- hosts: all
  roles:
     - knopki.sudoers
  tags: sudoers
  become: yes

#- hosts: all
#  roles:
#    - dj-wasabi.zabbix-agent
#  tags: zabbix-agent
#  become: yes
