---
- name: "SUDOERS | Install sudo (Debian-like)"
  apt: pkg=sudo state=installed update_cache=yes cache_valid_time={{ sudoers_apt_cache_valid_time }}
  when: ansible_os_family == "Debian"

- name: "SUDOERS | Install sudo (RedHat-like)"
  yum: name=sudo state=present
  when: ansible_os_family == "RedHat"

- name: "SUDOERS | Install sudo (SUSE-like)"
  zypper: name=sudo state=present
  when: ansible_os_family == "SUSE"

- name: "SUDOERS | Set includedir in sudoers"
  lineinfile:
    dest: /etc/sudoers
    line: "#includedir /etc/sudoers.d"
    state: present
    validate: "/usr/sbin/visudo -cf %s"

- name: "SUDOERS | Create sudoers"
  template:
    src: sudoers.d.j2
    dest: "/etc/sudoers.d/{{ item.filename }}"
    mode: 0440
    owner: root
    group: root
    validate: "/usr/sbin/visudo -cf %s"
  with_items:
    - "{{ sudoers }}"
    - "{{ additional_sudoers | default([]) }}"
  when: not sudoers_remove

- name: "SUDOERS | Remove sudoers"
  file:
    path: "/etc/sudoers.d/{{ sudoers_filename }}"
    state: absent
  with_items:
    - "{{ sudoers }}"
    - "{{additional_sudoers | default([])}}"
  when: sudoers_remove
